# Generated by Django 4.2.16 on 2024-10-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_businessuser_region_businessuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="businessuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="businessuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="regularuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="regularuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="regularuser",
            name="last_login",
        ),
        migrations.AddField(
            model_name="businessuser",
            name="region",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="businessuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="regularuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
