# Generated by Django 5.1.2 on 2024-10-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_regularuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
