# Generated by Django 5.1.2 on 2024-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_regularuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessuser',
            old_name='region',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='regularuser',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='regularuser',
            old_name='region',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], default='M', max_length=1),
        ),
    ]
