# Generated by Django 5.1.2 on 2024-10-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_region_businessuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], default='M', max_length=2),
        ),
    ]
