name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # GitHub 리포지토리에서 코드를 가져옵니다.

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # SSH 연결 설정
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} "
        cd /path/to/your/project  # EC2에서 프로젝트 폴더로 이동
        git pull origin main  # 최신 코드를 가져옴
        python3 -m venv venv  # 가상 환경 생성
        source venv/bin/activate  # 가상 환경 활성화
        pip install -r requirements.txt  # 필요 패키지 설치
        python manage.py migrate  # Django 마이그레이션
        python manage.py collectstatic --noinput  # 정적 파일 수집
        nohup python manage.py runserver 0.0.0.0:8000 &  # Django 서버 실행 (백그라운드)
        "
