name: Deploy to EC2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 실행

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # GitHub Secrets에 저장된 SSH Private Key 사용

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} "
        cd /home/ubuntu/backend  # 실제 프로젝트 경로로 이동
        git pull origin main  # 최신 코드 가져오기
        python3 -m venv venv  # 가상 환경 생성
        source venv/bin/activate  # 가상 환경 활성화
        pip install -r requirements.txt  # 필요한 패키지 설치
        python manage.py migrate  # 데이터베이스 마이그레이션 실행
        python manage.py collectstatic --noinput  # 정적 파일 수집
        nohup python manage.py runserver 0.0.0.0:8000 &  # 백그라운드에서 서버 실행
        "
