name: Build and deploy Django app to Azure Web App - backendazure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv backend/venv  # backend 폴더 내부에 venv 생성
          source backend/venv/bin/activate

      - name: Install dependencies
        run: |
          source backend/venv/bin/activate
          pip install -r backend/requirements.txt  # 경로 수정

      # Optional: Add step to run Django tests here (pytest, Django test suites, etc.)
      - name: Run Django tests
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test

      - name: Zip artifact for deployment
        run: zip -r release.zip backend -x '*.git*' -x 'backend/venv/*'  # backend 폴더만 압축 (venv 제외)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_BACKEND }}  # 백엔드용으로 생성된 Secret 사용

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'teambackend'
          package: 'backend'  # 압축 해제된 backend 폴더를 배포

      - name: Run database migrations
        run: |
          python backend/manage.py migrate  # venv 경로 설정 불필요 (Azure 환경에서)

      - name: Collect static files
        run: |
          python backend/manage.py collectstatic --noinput  # venv 경로 설정 불필요 (Azure 환경에서)
