name: Build and deploy Django app to Azure Web App - backendazure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # 리포지토리에서 코드를 가져옵니다

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv  # 가상환경 생성
          source venv/bin/activate  # 가상환경 활성화

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r backend/requirements.txt  # 의존성 설치 (backend 폴더 경로 명시)

      # Optional: Add step to run Django tests here (pytest, Django test suites, etc.)
      # 필요하다면 Django 테스트 실행

      - name: Zip artifact for deployment
        run: zip -r release.zip backend -x '*.git*' -x 'venv/*'  # backend 폴더만 압축

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # 웹앱 URL 출력
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_BACKEND }}  # 백엔드용 Azure 자격증명 사용

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'teambackend'  # 배포할 App Service 이름
          package: './backend'  # backend 폴더 경로 배포

      - name: Run database migrations
        run: |
          source venv/bin/activate
          python backend/manage.py migrate  # Django 마이그레이션 실행

      - name: Collect static files
        run: |
          source venv/bin/activate
          python backend/manage.py collectstatic --noinput  # 정적 파일 수집
