# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Deploy React App to Azure

on:
  push:
    branches:
      - main  # 메인 브랜치에 push될 때 배포

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 필요한 Node.js 버전

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend  # 프론트엔드 폴더 경로

    - name: Build the React app
      run: npm run build
      working-directory: ./frontend  # 프론트엔드 폴더 경로
      
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'frontendazure'
        slot-name: 'Production'
        package: .
          
